// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacieDeLaCharmeuse.Core.Data;

namespace PharmacieDeLaCharmeuse.Core.Data.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20200914190029_ProduitFinis")]
    partial class ProduitFinis
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Astuce", b =>
                {
                    b.Property<int>("AstuceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AstuceDuMois")
                        .HasColumnType("bit");

                    b.Property<int>("CategorieAstuceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEdition")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionCourte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("imageModelImageId")
                        .HasColumnType("int");

                    b.HasKey("AstuceId");

                    b.HasIndex("CategorieAstuceId");

                    b.HasIndex("imageModelImageId");

                    b.ToTable("Astuce");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieAstuce", b =>
                {
                    b.Property<int>("CategorieAstuceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionCategorieAstuce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCategorieAstuce")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieAstuceID");

                    b.ToTable("CategorieAstuce");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieProduit", b =>
                {
                    b.Property<int>("CategorieProduitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionCategorieProduit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCategorieProduit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieProduitID");

                    b.ToTable("CategorieProduit");

                    b.HasData(
                        new
                        {
                            CategorieProduitID = 1,
                            DescriptionCategorieProduit = "Médicament de premier niveau a recuper sans ordonance",
                            NomCategorieProduit = "Médicament sans ordonnace"
                        },
                        new
                        {
                            CategorieProduitID = 2,
                            DescriptionCategorieProduit = "Médicament de deuxieme niveau uniquement par ordonnance",
                            NomCategorieProduit = "Médicament avec ordonnace"
                        });
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.ImageModel", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Produit", b =>
                {
                    b.Property<int>("ProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategorieProduitId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionCourte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionLongue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnStock")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixPromo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ProduitDuMois")
                        .HasColumnType("bit");

                    b.HasKey("ProduitId");

                    b.HasIndex("CategorieProduitId");

                    b.ToTable("Produit");

                    b.HasData(
                        new
                        {
                            ProduitId = 1,
                            CategorieProduitId = 1,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 10,
                            ImageThumbnailUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            ImageUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            Nom = "Doliprane",
                            Prix = 2m,
                            PrixPromo = 1m,
                            ProduitDuMois = true
                        },
                        new
                        {
                            ProduitId = 2,
                            CategorieProduitId = 1,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 100,
                            ImageThumbnailUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            ImageUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            Nom = "Paracetamol",
                            Prix = 5m,
                            PrixPromo = 1m,
                            ProduitDuMois = true
                        },
                        new
                        {
                            ProduitId = 4,
                            CategorieProduitId = 2,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 10,
                            ImageThumbnailUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            ImageUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            Nom = "Doliprane",
                            Prix = 2m,
                            PrixPromo = 1m,
                            ProduitDuMois = true
                        },
                        new
                        {
                            ProduitId = 5,
                            CategorieProduitId = 2,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 105,
                            ImageThumbnailUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            ImageUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            Nom = "Sirop",
                            Prix = 5m,
                            PrixPromo = 1m,
                            ProduitDuMois = false
                        },
                        new
                        {
                            ProduitId = 6,
                            CategorieProduitId = 2,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 105,
                            ImageThumbnailUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            ImageUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            Nom = "Baume",
                            Prix = 15m,
                            PrixPromo = 16m,
                            ProduitDuMois = false
                        },
                        new
                        {
                            ProduitId = 3,
                            CategorieProduitId = 2,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 105,
                            ImageThumbnailUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            ImageUrL = "https://cdn.shop-pharmacie.fr/images/245x245/doliprane-paracetamol-1000-mg-comprimes-effervescents-F10000168-p10.jpg",
                            Nom = "contraception",
                            Prix = 15m,
                            PrixPromo = 16m,
                            ProduitDuMois = false
                        },
                        new
                        {
                            ProduitId = 7,
                            CategorieProduitId = 2,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 105,
                            ImageThumbnailUrL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.bobst.com%2Ffrfr%2Fsecteur-dutilisation-finale%2Fsoins-personnels%2Fproduits-pharmaceutiques%2F&psig=AOvVaw2a_bhGpZjpNdrQUOgPvNME&ust=1600195601907000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCOiAxq2n6esCFQAAAAAdAAAAABAE",
                            ImageUrL = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.bobst.com%2Ffrfr%2Fsecteur-dutilisation-finale%2Fsoins-personnels%2Fproduits-pharmaceutiques%2F&psig=AOvVaw2a_bhGpZjpNdrQUOgPvNME&ust=1600195601907000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCOiAxq2n6esCFQAAAAAdAAAAABAE",
                            Nom = "Lotion",
                            Prix = 15m,
                            PrixPromo = 16m,
                            ProduitDuMois = false
                        },
                        new
                        {
                            ProduitId = 8,
                            CategorieProduitId = 2,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 105,
                            ImageThumbnailUrL = "https://www.dinafem.org/uploads/sativex_3.jpg",
                            ImageUrL = "https://www.dinafem.org/uploads/sativex_3.jpg",
                            Nom = "dentifrice",
                            Prix = 15m,
                            PrixPromo = 16m,
                            ProduitDuMois = true
                        });
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.TestProduit", b =>
                {
                    b.Property<int>("TestProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEdition")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionCourte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumnailUrL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoteTest")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestProduitId");

                    b.ToTable("TestProduit");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Astuce", b =>
                {
                    b.HasOne("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieAstuce", "categorieAstuce")
                        .WithMany("Astuces")
                        .HasForeignKey("CategorieAstuceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacieDeLaCharmeuse.Core.Data.Models.ImageModel", "imageModel")
                        .WithMany()
                        .HasForeignKey("imageModelImageId");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Produit", b =>
                {
                    b.HasOne("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieProduit", "categorieProduit")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
