// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacieDeLaCharmeuse.Core.Data;

namespace PharmacieDeLaCharmeuse.Core.Data.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20200606135541_Firstmigration")]
    partial class Firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Astuce", b =>
                {
                    b.Property<int>("AstuceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("AstuceCategorieId")
                        .HasColumnType("int");

                    b.Property<string>("AstuceImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AstuceImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategorieAstuceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEdition")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionCourte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AstuceId");

                    b.HasIndex("CategorieAstuceID");

                    b.ToTable("Astuce");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.AstuceDuMois", b =>
                {
                    b.Property<int>("AstuceDuMoisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AstuceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Mois")
                        .HasColumnType("datetime2");

                    b.HasKey("AstuceDuMoisID");

                    b.ToTable("AstuceDuMois");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieAstuce", b =>
                {
                    b.Property<int>("CategorieAstuceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionCategorieAstuce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCategorieAstuce")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieAstuceID");

                    b.ToTable("CategorieAstuce");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieProduit", b =>
                {
                    b.Property<int>("CategorieProduitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionCategorieProduit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCategorieProduit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieProduitID");

                    b.ToTable("CategorieProduit");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.ImageModel", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Information", b =>
                {
                    b.Property<int>("InformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InformationId");

                    b.ToTable("Information");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Produit", b =>
                {
                    b.Property<int>("ProduitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.Property<int?>("CategorieProduitID")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionCourte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionLongue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnStock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Prix")
                        .HasColumnType("real");

                    b.Property<float>("PrixPromo")
                        .HasColumnType("real");

                    b.Property<string>("ProduitImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProduitImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProduitID");

                    b.HasIndex("CategorieProduitID");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.ProduitDuMois", b =>
                {
                    b.Property<int>("ProduitDuMoisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Mois")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.HasKey("ProduitDuMoisId");

                    b.ToTable("ProduitDuMois");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.TestDuMois", b =>
                {
                    b.Property<int>("TestDuMoisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Mois")
                        .HasColumnType("datetime2");

                    b.Property<int>("TestProduitId")
                        .HasColumnType("int");

                    b.HasKey("TestDuMoisId");

                    b.ToTable("TestDuMois");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.TestProduit", b =>
                {
                    b.Property<int>("TestProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEdition")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionCourte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoteTest")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestProduitId");

                    b.ToTable("TestProduit");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Astuce", b =>
                {
                    b.HasOne("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieAstuce", null)
                        .WithMany("Astuces")
                        .HasForeignKey("CategorieAstuceID");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Produit", b =>
                {
                    b.HasOne("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieProduit", null)
                        .WithMany("Produits")
                        .HasForeignKey("CategorieProduitID");
                });
#pragma warning restore 612, 618
        }
    }
}
