// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacieDeLaCharmeuse.Core.Data;

namespace PharmacieDeLaCharmeuse.Core.Data.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20200909123725_Initialisation")]
    partial class Initialisation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Astuce", b =>
                {
                    b.Property<int>("AstuceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AstuceDuMois")
                        .HasColumnType("bit");

                    b.Property<int>("CategorieAstuceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEdition")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionCourte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("imageModelImageId")
                        .HasColumnType("int");

                    b.HasKey("AstuceId");

                    b.HasIndex("CategorieAstuceId");

                    b.HasIndex("imageModelImageId");

                    b.ToTable("Astuce");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieAstuce", b =>
                {
                    b.Property<int>("CategorieAstuceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionCategorieAstuce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCategorieAstuce")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieAstuceID");

                    b.ToTable("CategorieAstuce");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieProduit", b =>
                {
                    b.Property<int>("CategorieProduitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionCategorieProduit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCategorieProduit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieProduitID");

                    b.ToTable("CategorieProduit");

                    b.HasData(
                        new
                        {
                            CategorieProduitID = 1,
                            DescriptionCategorieProduit = "Médicament de premier niveau a recuper sans ordonance",
                            NomCategorieProduit = "Médicament sans ordonnace"
                        },
                        new
                        {
                            CategorieProduitID = 2,
                            DescriptionCategorieProduit = "Médicament de deuxieme niveau uniquement par ordonnance",
                            NomCategorieProduit = "Médicament avec ordonnace"
                        });
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.ImageModel", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitreImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Information", b =>
                {
                    b.Property<int>("InformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InformationId");

                    b.ToTable("Information");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Produit", b =>
                {
                    b.Property<int>("ProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategorieProduitId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionCourte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionLongue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnStock")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrixPromo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ProduitDuMois")
                        .HasColumnType("bit");

                    b.HasKey("ProduitId");

                    b.HasIndex("CategorieProduitId");

                    b.ToTable("Produit");

                    b.HasData(
                        new
                        {
                            ProduitId = 1,
                            CategorieProduitId = 1,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 10,
                            ImageThumbnailUrL = "https://www.shutterstock.com/fr/image-photo/benon-france-november-7-2019close-box-1554031811",
                            ImageUrL = "https://www.shutterstock.com/fr/image-photo/benon-france-november-7-2019close-opened-1554031808",
                            Nom = "Doliprane",
                            Prix = 2m,
                            PrixPromo = 1m,
                            ProduitDuMois = true
                        },
                        new
                        {
                            ProduitId = 2,
                            CategorieProduitId = 1,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 100,
                            ImageThumbnailUrL = "https://www.shutterstock.com/fr/image-photo/benon-france-november-7-2019close-box-1554031811",
                            ImageUrL = "https://www.shutterstock.com/fr/image-photo/benon-france-november-7-2019close-opened-1554031808",
                            Nom = "Paracetamol",
                            Prix = 5m,
                            PrixPromo = 1m,
                            ProduitDuMois = true
                        },
                        new
                        {
                            ProduitId = 4,
                            CategorieProduitId = 2,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 10,
                            ImageThumbnailUrL = "https://www.shutterstock.com/fr/image-photo/benon-france-november-7-2019close-box-1554031811",
                            ImageUrL = "https://www.shutterstock.com/fr/image-photo/benon-france-november-7-2019close-opened-1554031808",
                            Nom = "Vaccin",
                            Prix = 2m,
                            PrixPromo = 1m,
                            ProduitDuMois = true
                        },
                        new
                        {
                            ProduitId = 5,
                            CategorieProduitId = 2,
                            DescriptionCourte = "Ici une Description courte",
                            DescriptionLongue = "ici une DescriptionLongue longue",
                            EnStock = 105,
                            ImageThumbnailUrL = "https://www.shutterstock.com/fr/image-photo/benon-france-november-7-2019close-box-1554031811",
                            ImageUrL = "https://www.shutterstock.com/fr/image-photo/benon-france-november-7-2019close-opened-1554031808",
                            Nom = "Sirop",
                            Prix = 5m,
                            PrixPromo = 1m,
                            ProduitDuMois = false
                        });
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.TestProduit", b =>
                {
                    b.Property<int>("TestProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEdition")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionCourte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumnailUrL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoteTest")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestProduitId");

                    b.ToTable("TestProduit");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Astuce", b =>
                {
                    b.HasOne("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieAstuce", "categorieAstuce")
                        .WithMany("Astuces")
                        .HasForeignKey("CategorieAstuceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmacieDeLaCharmeuse.Core.Data.Models.ImageModel", "imageModel")
                        .WithMany()
                        .HasForeignKey("imageModelImageId");
                });

            modelBuilder.Entity("PharmacieDeLaCharmeuse.Core.Data.Models.Produit", b =>
                {
                    b.HasOne("PharmacieDeLaCharmeuse.Core.Data.Models.CategorieProduit", "categorieProduit")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
